### PR TITLE
Moving storage folders result in "Permission Denied!"

### PR DESCRIPTION
**Pull request by osworx**
Using latest files from here.
Trying to move automatically the storage folders.
Result is a window with HTML-code.
Basically it says, that I have no permission to move "Permission Denied!" and the action was unsuccessfull!

This PR adds the permission to the admin group, otherwise it has to eb amde manually (but who knows that ..?)!

### CODE REVIEW

**Comment by condor2** [comment]
Yes. I forgot to add permission in database :)

**Comment by osworx** [comment]
> Yes. I forgot to add permission in database :)

Can happen :)

Other question: when do you think are you ready with the (basic) work (to be able to use that then in a productive environement?

**Comment by condor2** [comment]
As a NON PRO Developer I think will work just fine in production :)

**Comment by osworx** [comment]
> As a NON PRO Developer I think will work just fine in production :)

Okay, will see it in a view hours with some OCMods installed.

**Pull request merged**
